package export

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/bulaya-ute/appctl/internal/db"
)

const setupTmpl = `#!/usr/bin/env bash
# =============================================================================
# Setup script — generated by appctl
# Apps: {{.AppNames}}
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

ok()   { printf "${GREEN}  ✓  %s${NC}\n" "$*"; }
info() { printf "${CYAN}  →  %s${NC}\n" "$*"; }
warn() { printf "${YELLOW}  ⚠  %s${NC}\n" "$*"; }
die()  { printf "${RED}  ✗  %s${NC}\n" "$*" >&2; exit 1; }
h1()   { printf "\n${BOLD}  ══  %s  ══${NC}\n\n" "$*"; }

require_root() {
    [[ $EUID -eq 0 ]] || die "This script must be run as root (sudo bash setup.sh)"
}
require_root

# ── Stage 1: Prerequisites ────────────────────────────────────────────────────
h1 "Stage 1 — Prerequisites"
{{if .NeedsDotnet}}
if ! command -v dotnet &>/dev/null; then
    info "Installing .NET SDK..."
    wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O /tmp/pm.deb
    dpkg -i /tmp/pm.deb && apt-get update -q
    apt-get install -y dotnet-sdk-8.0
fi
if ! dotnet tool list -g 2>/dev/null | grep -q dotnet-ef; then
    dotnet tool install --global dotnet-ef
    export PATH="$PATH:$HOME/.dotnet/tools"
fi
ok ".NET SDK ready"
{{end}}
{{if .NeedsNode}}
if ! command -v node &>/dev/null; then
    info "Installing Node.js..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
fi
ok "Node.js ready ($(node --version))"
{{end}}
if ! command -v git &>/dev/null; then
    apt-get install -y git
fi
ok "Git ready"

# ── Stage 2: App setup ────────────────────────────────────────────────────────
{{range .Apps}}
h1 "App: {{.Name}} ({{.Type}})"

APP_DIR="{{.LocalPath}}"
{{if eq .Source "git"}}
if [[ ! -d "$APP_DIR/.git" ]]; then
    info "Cloning {{.GitRepoURL}} → $APP_DIR"
    mkdir -p "$(dirname "$APP_DIR")"
    git clone "{{.GitRepoURL}}" "$APP_DIR"
else
    info "Pulling latest (branch: {{.Branch}})"
    git -C "$APP_DIR" fetch --tags --prune
    git -C "$APP_DIR" checkout "{{.Branch}}"
    git -C "$APP_DIR" pull
fi
{{end}}

{{if eq .Type "dotnet-api"}}
PUBLISH_DIR="{{.EffectivePublishDir}}"
info "Building .NET API..."
dotnet publish "{{.LocalPath}}" -c Release -o "$PUBLISH_DIR"
ok "Build complete → $PUBLISH_DIR"
{{end}}

{{if or (eq .Type "react-spa") (eq .Type "static")}}
info "Installing npm dependencies..."
npm ci --prefix "{{.LocalPath}}"
info "Building..."
{{if .BuildCommand}}{{.BuildCommand}}{{else}}npm --prefix "{{.LocalPath}}" run build{{end}}
ok "Build complete → {{.EffectiveDistDir}}"
{{end}}

{{if .ServiceName}}
info "Writing systemd unit: {{.ServiceName}}"
cat > "/etc/systemd/system/{{.ServiceName}}.service" <<UNITEOF
[Unit]
Description=appctl: {{.Name}}
After=network.target

[Service]
Type=simple
WorkingDirectory={{.EffectiveWorkDir}}
ExecStart={{.EffectiveExecStart}}
Restart=always
RestartSec=10
{{- if .BindingPort}}
Environment=ASPNETCORE_URLS=http://localhost:{{.BindingPort}}
Environment=ASPNETCORE_ENVIRONMENT=Production
{{- end}}

[Install]
WantedBy=multi-user.target
UNITEOF
systemctl daemon-reload
systemctl enable "{{.ServiceName}}"
systemctl restart "{{.ServiceName}}"
ok "Service {{.ServiceName}} started"
{{end}}
{{end}}

# ── Summary ───────────────────────────────────────────────────────────────────
h1 "Setup complete"
{{range .Apps}}
printf "  %-24s %s\n" "{{.Name}}:" "{{.LocalPath}}"
{{- if .Domain}}
printf "  %-24s %s\n" "  domain:" "{{.Domain}}"
{{- end}}
{{- if .ServiceName}}
printf "  %-24s %s\n" "  service:" "{{.ServiceName}}"
{{- end}}
{{end}}
printf "\n"
{{if .HasCaddy}}
warn "Remember to configure your Caddyfile to serve these domains."
{{end}}
`

type appData struct {
	db.App
	EffectivePublishDir string
	EffectiveDistDir    string
	EffectiveWorkDir    string
	EffectiveExecStart  string
}

type templateData struct {
	AppNames   string
	Apps       []appData
	NeedsDotnet bool
	NeedsNode   bool
	HasCaddy    bool
}

func GenerateSetup(apps []db.App) (string, error) {
	data := templateData{}
	names := make([]string, 0, len(apps))

	for _, a := range apps {
		ad := appData{App: a}
		names = append(names, a.Name)

		switch a.Type {
		case db.AppTypeDotnetAPI:
			data.NeedsDotnet = true
			if a.PublishDir != "" {
				ad.EffectivePublishDir = a.PublishDir
			} else {
				ad.EffectivePublishDir = a.LocalPath + "/publish"
			}
			ad.EffectiveWorkDir = ad.EffectivePublishDir
			if a.RunCommand != "" {
				ad.EffectiveExecStart = a.RunCommand
			} else {
				ad.EffectiveExecStart = fmt.Sprintf("/usr/bin/dotnet %s/<App>.dll", ad.EffectivePublishDir)
			}
		case db.AppTypeReactSPA, db.AppTypeStatic:
			data.NeedsNode = true
			if a.PublishDir != "" {
				ad.EffectiveDistDir = a.PublishDir
			} else {
				ad.EffectiveDistDir = a.LocalPath + "/dist"
			}
		}

		if a.Domain != "" {
			data.HasCaddy = true
		}
		data.Apps = append(data.Apps, ad)
	}
	data.AppNames = strings.Join(names, ", ")

	tmpl, err := template.New("setup").Parse(setupTmpl)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
